### PR TITLE
Data Model

### PR DESCRIPTION
**Pull request by samiullahbahadur**
### **Project requirements**
**_I did the below tasks:_**

- [ ] Build your project schema.
- [ ] Create and run the necessary migration files.
- [ ] Table and column names should match the ERD diagram.
- [ ] note: photo for users table should be a link to an image
- [ ] Foreign keys should be included.
- [ ] All columns that are foreign keys should have a corresponding index.

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @samiullahbahadur, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

200w

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [x] Kindly make sure to implement all the changes as asked by the previous reviewer [here](https://github.com/samiullahbahadur/blog_app/pull/1).
## Don't open a new PR for re-review. You have to work on only one PR until it's approved.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by samiullahbahadur** [comment]
Hi  @sja-thedude you right,  but unfortunately to day I was used other computer when I pull  my repo
  I do merged feature branch to dev branch when I check the PR was closed .
 I don't know how  can restore the PR 
then I created new branch.
you be sure I implemented  all the changes as asked by the previous reviewer

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @samiullahbahadur 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
#### I am making this comment in the review summary because the relevant section is not in the files changed section of this pull request

- [ ] As stated by other reviewers, you still have `node_modules` pushed to the remote repository. To `gitignore` `node_modules` and remove it from the remote repository, kindly follow the steps in this [article](https://gist.github.com/apieceofbart/4ffa7aaee435ea2875b6d9c9395461ae)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by descholar-ceo — APPROVED** [review]
Hi @samiullahbahadur , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 Removed successfully `node_modules` as it was requested by the previous reviewer ✔️ 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
